// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: BlockBuf.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DeVote.Structures {

  /// <summary>Holder for reflection information generated from BlockBuf.proto</summary>
  public static partial class BlockBufReflection {

    #region Descriptor
    /// <summary>File descriptor for BlockBuf.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BlockBufReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5CbG9ja0J1Zi5wcm90bxIRRGVWb3RlLlN0cnVjdHVyZXMaH2dvb2dsZS9w",
            "cm90b2J1Zi90aW1lc3RhbXAucHJvdG8iqwIKCEJsb2NrQnVmEg4KBkhlaWdo",
            "dBgBIAEoBRIMCgRIYXNoGAIgASgJEi0KCVRpbWVzdGFtcBgDIAEoCzIaLmdv",
            "b2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASDQoFTWluZXIYBCABKAkSEAoIUHJl",
            "dkhhc2gYBSABKAkSCwoDblR4GAYgASgFEj0KDFRyYW5zYWN0aW9ucxgHIAMo",
            "CzInLkRlVm90ZS5TdHJ1Y3R1cmVzLkJsb2NrQnVmLlRyYW5zYWN0aW9uGmUK",
            "C1RyYW5zYWN0aW9uEgoKAklEGAEgASgFEigKBERhdGUYAiABKAsyGi5nb29n",
            "bGUucHJvdG9idWYuVGltZXN0YW1wEg8KB0VsZWN0b3IYAyABKAkSDwoHRWxl",
            "Y3RlZBgEIAEoCWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DeVote.Structures.BlockBuf), global::DeVote.Structures.BlockBuf.Parser, new[]{ "Height", "Hash", "Timestamp", "Miner", "PrevHash", "NTx", "Transactions" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::DeVote.Structures.BlockBuf.Types.Transaction), global::DeVote.Structures.BlockBuf.Types.Transaction.Parser, new[]{ "ID", "Date", "Elector", "Elected" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class BlockBuf : pb::IMessage<BlockBuf>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BlockBuf> _parser = new pb::MessageParser<BlockBuf>(() => new BlockBuf());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BlockBuf> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DeVote.Structures.BlockBufReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BlockBuf() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BlockBuf(BlockBuf other) : this() {
      height_ = other.height_;
      hash_ = other.hash_;
      timestamp_ = other.timestamp_ != null ? other.timestamp_.Clone() : null;
      miner_ = other.miner_;
      prevHash_ = other.prevHash_;
      nTx_ = other.nTx_;
      transactions_ = other.transactions_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BlockBuf Clone() {
      return new BlockBuf(this);
    }

    /// <summary>Field number for the "Height" field.</summary>
    public const int HeightFieldNumber = 1;
    private int height_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Height {
      get { return height_; }
      set {
        height_ = value;
      }
    }

    /// <summary>Field number for the "Hash" field.</summary>
    public const int HashFieldNumber = 2;
    private string hash_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Hash {
      get { return hash_; }
      set {
        hash_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Timestamp" field.</summary>
    public const int TimestampFieldNumber = 3;
    private global::Google.Protobuf.WellKnownTypes.Timestamp timestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    /// <summary>Field number for the "Miner" field.</summary>
    public const int MinerFieldNumber = 4;
    private string miner_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Miner {
      get { return miner_; }
      set {
        miner_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "PrevHash" field.</summary>
    public const int PrevHashFieldNumber = 5;
    private string prevHash_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PrevHash {
      get { return prevHash_; }
      set {
        prevHash_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nTx" field.</summary>
    public const int NTxFieldNumber = 6;
    private int nTx_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NTx {
      get { return nTx_; }
      set {
        nTx_ = value;
      }
    }

    /// <summary>Field number for the "Transactions" field.</summary>
    public const int TransactionsFieldNumber = 7;
    private static readonly pb::FieldCodec<global::DeVote.Structures.BlockBuf.Types.Transaction> _repeated_transactions_codec
        = pb::FieldCodec.ForMessage(58, global::DeVote.Structures.BlockBuf.Types.Transaction.Parser);
    private readonly pbc::RepeatedField<global::DeVote.Structures.BlockBuf.Types.Transaction> transactions_ = new pbc::RepeatedField<global::DeVote.Structures.BlockBuf.Types.Transaction>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::DeVote.Structures.BlockBuf.Types.Transaction> Transactions {
      get { return transactions_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BlockBuf);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BlockBuf other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Height != other.Height) return false;
      if (Hash != other.Hash) return false;
      if (!object.Equals(Timestamp, other.Timestamp)) return false;
      if (Miner != other.Miner) return false;
      if (PrevHash != other.PrevHash) return false;
      if (NTx != other.NTx) return false;
      if(!transactions_.Equals(other.transactions_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Height != 0) hash ^= Height.GetHashCode();
      if (Hash.Length != 0) hash ^= Hash.GetHashCode();
      if (timestamp_ != null) hash ^= Timestamp.GetHashCode();
      if (Miner.Length != 0) hash ^= Miner.GetHashCode();
      if (PrevHash.Length != 0) hash ^= PrevHash.GetHashCode();
      if (NTx != 0) hash ^= NTx.GetHashCode();
      hash ^= transactions_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Height != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Height);
      }
      if (Hash.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Hash);
      }
      if (timestamp_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Timestamp);
      }
      if (Miner.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Miner);
      }
      if (PrevHash.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(PrevHash);
      }
      if (NTx != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(NTx);
      }
      transactions_.WriteTo(output, _repeated_transactions_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Height != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Height);
      }
      if (Hash.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Hash);
      }
      if (timestamp_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Timestamp);
      }
      if (Miner.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Miner);
      }
      if (PrevHash.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(PrevHash);
      }
      if (NTx != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(NTx);
      }
      transactions_.WriteTo(ref output, _repeated_transactions_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Height != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Height);
      }
      if (Hash.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Hash);
      }
      if (timestamp_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Timestamp);
      }
      if (Miner.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Miner);
      }
      if (PrevHash.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PrevHash);
      }
      if (NTx != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NTx);
      }
      size += transactions_.CalculateSize(_repeated_transactions_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BlockBuf other) {
      if (other == null) {
        return;
      }
      if (other.Height != 0) {
        Height = other.Height;
      }
      if (other.Hash.Length != 0) {
        Hash = other.Hash;
      }
      if (other.timestamp_ != null) {
        if (timestamp_ == null) {
          Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        Timestamp.MergeFrom(other.Timestamp);
      }
      if (other.Miner.Length != 0) {
        Miner = other.Miner;
      }
      if (other.PrevHash.Length != 0) {
        PrevHash = other.PrevHash;
      }
      if (other.NTx != 0) {
        NTx = other.NTx;
      }
      transactions_.Add(other.transactions_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Height = input.ReadInt32();
            break;
          }
          case 18: {
            Hash = input.ReadString();
            break;
          }
          case 26: {
            if (timestamp_ == null) {
              Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Timestamp);
            break;
          }
          case 34: {
            Miner = input.ReadString();
            break;
          }
          case 42: {
            PrevHash = input.ReadString();
            break;
          }
          case 48: {
            NTx = input.ReadInt32();
            break;
          }
          case 58: {
            transactions_.AddEntriesFrom(input, _repeated_transactions_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Height = input.ReadInt32();
            break;
          }
          case 18: {
            Hash = input.ReadString();
            break;
          }
          case 26: {
            if (timestamp_ == null) {
              Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Timestamp);
            break;
          }
          case 34: {
            Miner = input.ReadString();
            break;
          }
          case 42: {
            PrevHash = input.ReadString();
            break;
          }
          case 48: {
            NTx = input.ReadInt32();
            break;
          }
          case 58: {
            transactions_.AddEntriesFrom(ref input, _repeated_transactions_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the BlockBuf message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public sealed partial class Transaction : pb::IMessage<Transaction>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Transaction> _parser = new pb::MessageParser<Transaction>(() => new Transaction());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Transaction> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::DeVote.Structures.BlockBuf.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Transaction() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Transaction(Transaction other) : this() {
          iD_ = other.iD_;
          date_ = other.date_ != null ? other.date_.Clone() : null;
          elector_ = other.elector_;
          elected_ = other.elected_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Transaction Clone() {
          return new Transaction(this);
        }

        /// <summary>Field number for the "ID" field.</summary>
        public const int IDFieldNumber = 1;
        private int iD_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int ID {
          get { return iD_; }
          set {
            iD_ = value;
          }
        }

        /// <summary>Field number for the "Date" field.</summary>
        public const int DateFieldNumber = 2;
        private global::Google.Protobuf.WellKnownTypes.Timestamp date_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Google.Protobuf.WellKnownTypes.Timestamp Date {
          get { return date_; }
          set {
            date_ = value;
          }
        }

        /// <summary>Field number for the "Elector" field.</summary>
        public const int ElectorFieldNumber = 3;
        private string elector_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Elector {
          get { return elector_; }
          set {
            elector_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "Elected" field.</summary>
        public const int ElectedFieldNumber = 4;
        private string elected_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Elected {
          get { return elected_; }
          set {
            elected_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as Transaction);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Transaction other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (ID != other.ID) return false;
          if (!object.Equals(Date, other.Date)) return false;
          if (Elector != other.Elector) return false;
          if (Elected != other.Elected) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (ID != 0) hash ^= ID.GetHashCode();
          if (date_ != null) hash ^= Date.GetHashCode();
          if (Elector.Length != 0) hash ^= Elector.GetHashCode();
          if (Elected.Length != 0) hash ^= Elected.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (ID != 0) {
            output.WriteRawTag(8);
            output.WriteInt32(ID);
          }
          if (date_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(Date);
          }
          if (Elector.Length != 0) {
            output.WriteRawTag(26);
            output.WriteString(Elector);
          }
          if (Elected.Length != 0) {
            output.WriteRawTag(34);
            output.WriteString(Elected);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (ID != 0) {
            output.WriteRawTag(8);
            output.WriteInt32(ID);
          }
          if (date_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(Date);
          }
          if (Elector.Length != 0) {
            output.WriteRawTag(26);
            output.WriteString(Elector);
          }
          if (Elected.Length != 0) {
            output.WriteRawTag(34);
            output.WriteString(Elected);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (ID != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(ID);
          }
          if (date_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Date);
          }
          if (Elector.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Elector);
          }
          if (Elected.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Elected);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Transaction other) {
          if (other == null) {
            return;
          }
          if (other.ID != 0) {
            ID = other.ID;
          }
          if (other.date_ != null) {
            if (date_ == null) {
              Date = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            Date.MergeFrom(other.Date);
          }
          if (other.Elector.Length != 0) {
            Elector = other.Elector;
          }
          if (other.Elected.Length != 0) {
            Elected = other.Elected;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                ID = input.ReadInt32();
                break;
              }
              case 18: {
                if (date_ == null) {
                  Date = new global::Google.Protobuf.WellKnownTypes.Timestamp();
                }
                input.ReadMessage(Date);
                break;
              }
              case 26: {
                Elector = input.ReadString();
                break;
              }
              case 34: {
                Elected = input.ReadString();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                ID = input.ReadInt32();
                break;
              }
              case 18: {
                if (date_ == null) {
                  Date = new global::Google.Protobuf.WellKnownTypes.Timestamp();
                }
                input.ReadMessage(Date);
                break;
              }
              case 26: {
                Elector = input.ReadString();
                break;
              }
              case 34: {
                Elected = input.ReadString();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
